### ISSUE TITLE
"Checkbox" component

### ISSUE THREAD

**Issue by emeaguiar** [10up/wp-component-library#143]
I write "checkbox" in quotes because I don't really know if this counts as checkbox... But anyways.

Lately I've had a couple projects where we need maybe a checkbox form, or a radio form. I have found the default design/styling to not be really good, and clients often ask for a redesign.

What I have found to work is more of a "tag" style, so instead of label + checkbox. I only add a label, that acts as a checkbox. I want to know what you guys think about this kind of thing. I prepared a quick codepen for it:

http://codepen.io/emeaguiar/pen/NRJQAb

![image](https://cloud.githubusercontent.com/assets/1379732/19709926/1336ddf6-9af0-11e6-9978-4a2d8e52f0de.png)

**Comment by timwright12** [comment]
@kdo This one almost feels like it's faster to custom code rather than pulling in a component

**Comment by kdo** [comment]
@tim-west @emeaguiar agree, I've done several of those recently and they're all different. Closing
