### ISSUE TITLE
New Component - "service card".

### ISSUE THREAD

**Issue by seothemes** [10up/wp-component-library#165]
It would be great to have a component similar to author cards but for services. This is a really common component for WordPress themes or websites in general.

The correct schema can be found here [https://schema.org/Service](https://schema.org/Service)

![screen shot 2017-03-18 at 5 15 33 pm](https://cloud.githubusercontent.com/assets/24793388/24070777/a687d478-0bfe-11e7-988a-4484a847da36.png)

**Comment by kdo** [comment]
Hi @seothemes,

I think this component would stray to far away from WordPress core output, and we wouldn't have anything to add to https://schema.org/Service in terms of markup example.

Thanks!
