### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by emeaguiar** [10up/wp-component-library#166]
Since we already have "Download SCSS", how about a "copy to clipboard" functionality for the markup, I'm thinking this more for the HTML part of the components, since the only way to get them is to select all and copy, we can reduce this process even more.

**Comment by kdo** [comment]
@emeaguiar good idea, working on it!

**Comment by cehfisher** [comment]
i used this project for that kind of functionality - https://zenorocha.github.io/clipboard.js
it was nice to see the visual `copied` text appear. plus it's pretty accessible out of the box.
![copy](https://cloud.githubusercontent.com/assets/15240149/26465069/7d4fe2c2-414f-11e7-850c-d1ebe296a268.gif)

**Comment by kdo** [comment]
Thanks @cehfisher! This is actually what I am using as well 👍  :)

**Comment by kdo** [comment]
@emeaguiar copy to clipboard button has been added everywhere! Can you test and close this issue if all is good?

Thanks!

**Comment by emeaguiar** [comment]
Looking good!
