### ISSUE TITLE
Tabs component using improper roles and ARIA

### ISSUE THREAD

**Issue by Firestorm980** [10up/wp-component-library#170]
The current tabs component has a few outstanding issues that are affecting its use with various screen readers (specifically "Narrator" in Windows 10). This issue is mainly for a note for our current refactor so that it can be resolved when working on that (hence the "won't fix"). There will also be an issue posted in that repo as well (just in case).

The component is missing the following role attributes:
- tablist
- tab
- tabpanel

Additionally, tab items are missing the following ARIA attributes:
- aria-controls
- aria-setsize
- aria-posinset

**Comment by timwright12** [comment]
@Firestorm980 did this stuff get into the new component? https://github.com/10up/component-tabs

**Comment by samikeijonen** [comment]
I'm not familiar with the last two and they are not mentioned in [ARIA practises for tabs](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel).

**Comment by Firestorm980** [comment]
@timwright12 I don't believe it was integrated. Tabs was one of the first ones converted (I think at the Summit itself), and this issue was just after that. Can add an issue there.

@samikeijonen They are mentioned https://www.w3.org/TR/wai-aria-1.1/#tab as supported properties. I had previously not heard of them either. From most examples, they seem to be treated as optional. I think most readers are able to figure out the count and position by themselves, but Narrator seems especially picky about some of these things (and breaks the components sometimes when they aren't around).

**Comment by colorful-tones** [comment]
This was addressed in the new version of the Tabs component. Closing this out.
https://github.com/10up/component-tabs/issues/1
