### ISSUE TITLE
New Component: Countdown Timer

### ISSUE THREAD

**Issue by timwright12** [10up/wp-component-library#206]

**Comment by dkoo** [comment]
Just jotting notes about a generalized approach we could take here. I worked on a simple countdown clock for another project which worked like so:

- The component is passed a single param/prop/argument: some future time to count down to, in UNIX timestamp format. The reason for UNIX is that we can avoid manually dealing with time zones and let the device/browser determine local time based on UNIX. 
- On init, start a `setInterval` function that runs once every second. Make sure to cache the reference to that interval so we can clear it if needed.
- Within that interval function, check the current time in UNIX format (`new Date().valueOf()`).
- Subtract the current time from the future time. This diff is your countdown period in milliseconds. Calculating the diff on every interval function call lets us avoid discrepancies if JS execution gets out of sync with real time.
- Format the milliseconds however you like (e.g. DD:HH:MM:SS) for display.
- Update the display.
- If the diff hits 0 or the future time is no longer in the future, clear the interval.

**Comment by dkoo** [comment]
And here's a quick (not thoroughly tested) function to parse milliseconds into DD:HH:MM:SS for display:

```javascript
const formatDiff = ( milliseconds ) => {
    const msPerDay = 24 * 60 * 60 * 1000;
    const msPerHour = 60 * 60 * 1000;
    const msPerMinute = 60 * 1000;
    const msPerSecond = 1000;

    let days = Math.floor( milliseconds / msPerDay );
    let hours = Math.floor( ( milliseconds - days * msPerDay ) / msPerHour );
    let minutes = Math.round( ( milliseconds - days * msPerDay - hours * msPerHour ) / msPerMinute );
    let seconds = Math.round( ( milliseconds - days * msPerDay - hours * msPerHour - minutes * msPerMinute ) / msPerSecond );
    
    const pad = n => ( n < 10 ? '0' + n : n );

    if ( seconds < 0 ) {
        minutes --;
        seconds += 60;
    }

    if ( minutes === 60 ) {
        hours ++;
        minutes = 0;
    }

    if ( hours === 24 ) {
        days ++;
        hours = 0;
    }

    return [ pad( days ), pad( hours ), pad( minutes ), pad( seconds ) ].join( ' : ' );
}
```

**Comment by timwright12** [comment]
this is released
