### ISSUE TITLE
[docs] Page Titles and Descriptions

### ISSUE THREAD

**Issue by timwright12** [10up/wp-component-library#214]
Page titles and descriptions help Google understand what a web page is about. Google spends a lot of effort trying to decipher what a web page is about, and in some cases may have difficulty in doing so.
Page titles and descriptions are ideal places to add keywords as they spell out to Google what search result page should rank for. Pages with missing or duplicate metadata reduce the overall chances for the website to rank as many terms as possible. 

Web pages should also have unique sets of metadata to avoid duplication. When crawling the library, we found there were 18 pages with the same Page Title and 19 pages with missing Meta descriptions. We would recommend to create unique sets of [Page Titles and Meta Descriptions](https://docs.google.com/spreadsheets/d/1l6l2iIzQAewLgkf8Dap5a4qZSQWiubvrGBXtaO3pVfA/edit?usp=sharing) for these pages and if possible, include a relevant keyword for each page.

**Comment by timwright12** [comment]
Assigned to Fabian

**Comment by fabiankaegy** [comment]
@timwright12 do you want the seo title to be a custom variable that can be set individually or just go with the page title? 

Also any preference about dividers in titles?
1. `Baseline | A Component Library from 10up — {{ page.title }}`
2. `Baseline | A Component Library from 10up - {{ page.title }}`
3. `Baseline | A Component Library from 10up | {{ page.title }}`
